[build]
  command = "npm run build"
  publish = "/build"
  base ="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  # Add environment variables (if any)
  NODE_ENV = "production"

[build.environment]
  # Set the Node.js version for the build environment
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-functions-installation"
